export const navigationGroups = [
  {
    title: "Workspace",
    links: [
      { label: "Test Area Home", path: "/v2", icon: "LayoutDashboard" },
      { label: "Workspace Launcher", path: "/v2/workspaces", icon: "LayoutDashboard" },
      { label: "Developer Portal", path: "/v2/developer", icon: "Code2" },
      { label: "Communication Monitor", path: "/v2/developer/communication-monitor", icon: "Activity" },
      { label: "Automation Center", path: "/v2/developer/automation-center", icon: "Workflow" },
      { label: "Event Processor", path: "/v2/developer/event-processor", icon: "GitBranch" },
      { label: "Geofence Simulator", path: "/v2/developer/geofence-simulator", icon: "MapPinned" },
      { label: "Delivery Diagnostics", path: "/v2/developer/delivery-diagnostics", icon: "ShieldCheck" },
      { label: "Client Management", path: "/v2/developer/client-management", icon: "UserRound" },
      { label: "Mobile Portal", path: "/mobile", icon: "Smartphone" },
    ],
  },
  {
    title: "Dispatch",
    links: [
      { label: "Dispatch Home", path: "/v2/dispatch", icon: "Activity" },
      { label: "Daily Dashboard", path: "/v2/dispatch/dashboard", icon: "LayoutDashboard" },
      { label: "Planning", path: "/v2/dispatch/planning", icon: "CalendarDays" },
      { label: "Load Builder", path: "/v2/dispatch/load-builder", icon: "ClipboardPlus" },
      { label: "Approval Queue", path: "/v2/dispatch/approval-queue", icon: "ClipboardCheck" },
      { label: "Tender Queue", path: "/v2/dispatch/tender-queue", icon: "ClipboardList" },
      { label: "Active Loads", path: "/v2/dispatch/active-loads", icon: "Truck" },
      { label: "Completed Loads", path: "/v2/dispatch/completed-loads", icon: "CheckCircle2" },
      { label: "Exceptions", path: "/v2/dispatch/exceptions", icon: "TriangleAlert" },
      { label: "Performance", path: "/v2/dispatch/performance", icon: "BarChart3" },
    ],
  },
  {
    title: "Partner Portals",
    links: [
      { label: "Broker Workspace", path: "/v2/broker", icon: "Handshake" },
      { label: "Carrier Workspace", path: "/v2/carrier", icon: "Warehouse" },
      { label: "Driver Workspace", path: "/v2/driver", icon: "UserRound" },
      { label: "Shipper Portal", path: "/portal/shipper", icon: "Building2" },
      { label: "Broker Portal", path: "/portal/broker", icon: "Briefcase" },
      { label: "Carrier Portal", path: "/portal/carrier", icon: "Truck" },
      { label: "Driver Portal", path: "/portal/driver", icon: "User" },
    ],
  },
  {
    title: "Visibility",
    links: [
      { label: "Notifications", path: "/v2/dispatch/notifications", icon: "Bell" },
      { label: "Communication Log", path: "/v2/dispatch/communication-log", icon: "MessageSquareText" },
      { label: "Communication Actions", path: "/v2/dispatch/communication-actions", icon: "Send" },
      { label: "Driver Attestation Test", path: "/v2/dispatch/driver-attestation-test", icon: "MessageCircleReply" },
      { label: "Event History", path: "/v2/dispatch/events", icon: "History" },
      { label: "GPS Tracking", path: "/v2/dispatch/gps", icon: "MapPinned" },
      { label: "Location Master", path: "/v2/dispatch/locations", icon: "Map" },
    ],
  },
];
