import { useEffect, useState } from "react";
import { generateClient } from "aws-amplify/data";
import type { Schema } from "../../../amplify/data/resource";
import { formatEasternDateTime } from "../../utils/dateTime";

const client = generateClient<Schema>();

type LoadEventRecord = Schema["LoadEvent"]["type"];

export default function EventProcessorMonitor() {
  const [events, setEvents] = useState<LoadEventRecord[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [sourceFilter, setSourceFilter] = useState("ALL");
  const [eventFilter, setEventFilter] = useState("ALL");
  const [loadFilter, setLoadFilter] = useState("");

  async function loadEvents() {
    setIsLoading(true);
    const result = await client.models.LoadEvent.list();
    const sorted = [...result.data].sort((a, b) =>
      String(b.eventTime ?? "").localeCompare(String(a.eventTime ?? ""))
    );
    setEvents(sorted);
    setIsLoading(false);
  }

  useEffect(() => {
    loadEvents();
  }, []);

  const sources = Array.from(new Set(events.map((e) => String(e.eventSource ?? "")).filter(Boolean))).sort();
  const eventTypes = Array.from(new Set(events.map((e) => String(e.eventType ?? "")).filter(Boolean))).sort();

  const filteredEvents = events.filter((event) => {
    const matchesSource = sourceFilter === "ALL" || event.eventSource === sourceFilter;
    const matchesEvent = eventFilter === "ALL" || event.eventType === eventFilter;
    const matchesLoad =
      !loadFilter ||
      String(event.loadId ?? "").toLowerCase().includes(loadFilter.toLowerCase());

    return matchesSource && matchesEvent && matchesLoad;
  });

  const totalEvents = events.length;
  const smsEvents = events.filter((e) => e.eventSource === "SMS").length;
  const geofenceEvents = events.filter((e) => e.eventSource === "GEOFENCE").length;
  const plannerEvents = events.filter((e) => e.eventSource === "PLANNER").length;

  return (
    <section>
      <div className="page-header">
        <div>
          <h2>Event Processor Monitor</h2>
          <p>
            Developer visibility into system events generated by SMS,
            planner actions, ETA updates, geofence triggers, and future
            driver app telemetry.
          </p>
        </div>

        <button onClick={loadEvents}>Refresh</button>
      </div>

      <div className="dashboard-grid">
        <div className="card"><h2>Total Events</h2><p>{totalEvents}</p></div>
        <div className="card"><h2>SMS Events</h2><p>{smsEvents}</p></div>
        <div className="card"><h2>Geofence Events</h2><p>{geofenceEvents}</p></div>
        <div className="card"><h2>Planner Events</h2><p>{plannerEvents}</p></div>
      </div>

      <div className="table-card">
        <h2>Filters</h2>

        <div className="action-row">
          <select value={sourceFilter} onChange={(e) => setSourceFilter(e.target.value)}>
            <option value="ALL">All Sources</option>
            {sources.map((source) => (
              <option key={source} value={source}>{source}</option>
            ))}
          </select>

          <select value={eventFilter} onChange={(e) => setEventFilter(e.target.value)}>
            <option value="ALL">All Event Types</option>
            {eventTypes.map((eventType) => (
              <option key={eventType} value={eventType}>{eventType}</option>
            ))}
          </select>

          <input
            value={loadFilter}
            onChange={(e) => setLoadFilter(e.target.value)}
            placeholder="Filter by Load ID"
          />

          <button
            onClick={() => {
              setSourceFilter("ALL");
              setEventFilter("ALL");
              setLoadFilter("");
            }}
          >
            Clear Filters
          </button>
        </div>
      </div>

      <div className="table-card">
        <h2>Event Stream</h2>
        <p>{filteredEvents.length} of {events.length} events shown.</p>

        {isLoading ? (
          <p>Loading event processor records...</p>
        ) : (
          <table>
            <thead>
              <tr>
                <th>Event Time</th>
                <th>Source</th>
                <th>Event Type</th>
                <th>Load</th>
                <th>Notes</th>
              </tr>
            </thead>

            <tbody>
              {filteredEvents.map((event) => (
                <tr key={event.id}>
                  <td>{formatEasternDateTime(event.eventTime)}</td>
                  <td>{event.eventSource}</td>
                  <td>{event.eventType}</td>
                  <td>{event.loadId}</td>
                  <td>{event.notes}</td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </section>
  );
}
